import { alpha, type Theme } from "../util.ts";

// ---- Palette ----------------------------------------------------------

// Backgrounds (lightest → darkest)
const bg = "#faf8fd";
const bgPanel = "#efe9f7";
const bgRaised = "#e6ddf2";
const bgHover = "#e6dcf2";
const bgSelected = "#ddd0ed";
const bgButtonHover = "#d1c0e6";
const bgInactiveTab = "#dccfee";
const bgMinimap = "#f1ebf9";

// Text
const fg = "#1d1432";
const fgStrong = "#2e1f4e";
const fgMuted = "#6d5c8c";
const fgComment = "#8c80a5";
const fgFaint = "#a99cc2";

// Borders / guides
const border = "#cdbde6";
const guide = "#e0d4ee";

// Family accents
const purple = "#6c4bc1";
const purpleHover = "#5c3ea8";
const teal = "#7bcdc2";
const tealDeep = "#3aa195";
const tealText = "#2a8a82";

// Token-only colours
const fnBlue = "#1f6e8c";
const propBlue = "#3a7a90";
const paramBrown = "#a04020";
const warm = "#b85a00";

// Standard / shared semantics
const green = "#00a000";
const red = "#cd0365";
const orange = "#e7645c";
const blue = "#2a94d6";
const lightGreen = "#4cd07a";
const lightOrange = "#f5a070";
const lightBlue = "#6ab7e8";
const lightCyan = "#9ee0d6";
const lightPurple = "#b4a3e8";
const ansiBlack = "#1a2a1a";
const ansiGrey = "#7a8a78";
const white = "#ffffff";
const black = "#000000";
const transparent = "#00000000";

// ---- Theme ------------------------------------------------------------

const theme: Theme = {
  $schema: "vscode://schemas/color-theme",
  name: "micro:bit Halo Light",
  type: "light",
  semanticHighlighting: true,
  colors: {
    "editor.background": bg,
    "editor.foreground": fg,
    "editor.lineHighlightBackground": alpha(purple, 0.05),
    "editor.lineHighlightBorder": transparent,
    "editor.selectionBackground": alpha(teal, 0.3),
    "editor.inactiveSelectionBackground": alpha(teal, 0.3),
    "editor.findMatchBackground": alpha(purple, 0.12),
    "editor.findMatchHighlightBackground": alpha(purple, 0.12),
    "editor.wordHighlightBackground": alpha(purple, 0.12),
    "editorCursor.foreground": purple,
    "editorLineNumber.foreground": fgFaint,
    "editorLineNumber.activeForeground": fg,
    "editorBracketMatch.background": alpha(purple, 0.12),
    "editorBracketMatch.border": purple,
    "editorWhitespace.foreground": fgFaint + "55",
    "editorIndentGuide.background": guide,
    "editorIndentGuide.activeBackground": fgFaint,
    "editorRuler.foreground": guide,
    "editorBracketHighlight.foreground1": purple,
    "editorBracketHighlight.foreground2": tealText,
    "editorBracketHighlight.foreground3": red,
    "editorBracketHighlight.foreground4": purple,
    "editorBracketHighlight.foreground5": tealText,
    "editorBracketHighlight.foreground6": red,
    "editorBracketHighlight.unexpectedBracket.foreground": red,
    "editorGutter.background": bg,
    "editorGutter.modifiedBackground": teal,
    "editorGutter.addedBackground": green,
    "editorGutter.deletedBackground": red,
    "titleBar.activeBackground": bgRaised,
    "titleBar.activeForeground": fgStrong,
    "titleBar.inactiveBackground": bgRaised,
    "titleBar.inactiveForeground": fgMuted,
    "titleBar.border": border,
    "activityBar.background": purple,
    "activityBar.foreground": white,
    "activityBar.inactiveForeground": alpha(white, 0.65),
    "activityBar.activeBorder": white,
    "activityBar.activeBackground": transparent,
    "activityBar.border": purple,
    "activityBarBadge.background": orange,
    "activityBarBadge.foreground": white,
    "sideBar.background": bgPanel,
    "sideBar.foreground": fgStrong,
    "sideBar.border": border,
    "sideBarTitle.foreground": fgMuted,
    "sideBarSectionHeader.background": bgPanel,
    "sideBarSectionHeader.foreground": fgMuted,
    "sideBarSectionHeader.border": guide,
    "list.activeSelectionBackground": bgSelected,
    "list.activeSelectionForeground": fgStrong,
    "list.inactiveSelectionBackground": bgSelected,
    "list.inactiveSelectionForeground": fgStrong,
    "list.hoverBackground": bgHover,
    "list.hoverForeground": fgStrong,
    "list.focusBackground": bgSelected,
    "list.focusForeground": fgStrong,
    "list.focusOutline": purple,
    "list.highlightForeground": purple,
    "tree.indentGuidesStroke": guide,
    "editorGroupHeader.tabsBackground": bgRaised,
    "editorGroupHeader.tabsBorder": border,
    "editorGroupHeader.border": border,
    "tab.activeBackground": bg,
    "tab.activeForeground": fg,
    "tab.activeBorderTop": purple,
    "tab.activeBorder": bg,
    "tab.inactiveBackground": bgInactiveTab,
    "tab.inactiveForeground": fgMuted,
    "tab.hoverBackground": bgHover,
    "tab.border": border,
    "tab.unfocusedActiveBorderTop": guide,
    "editorGroup.border": border,
    "breadcrumb.background": bg,
    "breadcrumb.foreground": fgMuted,
    "breadcrumb.focusForeground": fg,
    "breadcrumb.activeSelectionForeground": purple,
    "statusBar.background": tealDeep,
    "statusBar.foreground": white,
    "statusBar.border": tealDeep,
    "statusBar.noFolderBackground": tealDeep,
    "statusBar.debuggingBackground": purple,
    "statusBar.debuggingForeground": white,
    "statusBarItem.hoverBackground": alpha(white, 0.13),
    "statusBarItem.remoteBackground": alpha(black, 0.13),
    "statusBarItem.remoteForeground": white,
    "statusBarItem.prominentBackground": alpha(black, 0.13),
    "statusBarItem.errorBackground": red,
    "statusBarItem.warningBackground": warm,
    "panel.background": bg,
    "panel.border": border,
    "panelTitle.activeForeground": fg,
    "panelTitle.inactiveForeground": fgMuted,
    "panelTitle.activeBorder": purple,
    "terminal.background": bg,
    "terminal.foreground": fg,
    "terminal.ansiBlack": ansiBlack,
    "terminal.ansiRed": red,
    "terminal.ansiGreen": green,
    "terminal.ansiYellow": orange,
    "terminal.ansiBlue": blue,
    "terminal.ansiMagenta": purple,
    "terminal.ansiCyan": teal,
    "terminal.ansiWhite": ansiBlack,
    "terminal.ansiBrightBlack": ansiGrey,
    "terminal.ansiBrightRed": orange,
    "terminal.ansiBrightGreen": lightGreen,
    "terminal.ansiBrightYellow": lightOrange,
    "terminal.ansiBrightBlue": lightBlue,
    "terminal.ansiBrightMagenta": lightPurple,
    "terminal.ansiBrightCyan": lightCyan,
    "terminal.ansiBrightWhite": black,
    "minimap.background": bgMinimap,
    "minimap.selectionHighlight": purple,
    "minimapSlider.background": alpha(purple, 0.12),
    "minimapSlider.hoverBackground": alpha(purple, 0.12),
    "minimapSlider.activeBackground": alpha(purple, 0.12),
    "minimapGutter.modifiedBackground": teal,
    "minimapGutter.addedBackground": green,
    "minimapGutter.deletedBackground": red,
    "input.background": bg,
    "input.foreground": fg,
    "input.border": border,
    "input.placeholderForeground": fgMuted,
    "inputOption.activeBorder": purple,
    "dropdown.background": bg,
    "dropdown.foreground": fg,
    "dropdown.border": border,
    "button.background": purple,
    "button.foreground": white,
    "button.hoverBackground": purpleHover,
    "button.secondaryBackground": bgSelected,
    "button.secondaryForeground": fgStrong,
    "button.secondaryHoverBackground": bgButtonHover,
    "badge.background": purple,
    "badge.foreground": white,
    "notificationCenter.border": border,
    "notifications.background": bgPanel,
    "notifications.foreground": fgStrong,
    "notifications.border": border,
    "textLink.foreground": purple,
    "textLink.activeForeground": purple,
    "editorLink.activeForeground": purple,
    "focusBorder": purple,
    "contrastBorder": transparent,
    "scrollbar.shadow": alpha(black, 0.13),
    "scrollbarSlider.background": alpha(fgFaint, 0.27),
    "scrollbarSlider.hoverBackground": alpha(fgFaint, 0.4),
    "scrollbarSlider.activeBackground": alpha(fgFaint, 0.53),
    "diffEditor.insertedTextBackground": alpha(green, 0.18),
    "diffEditor.removedTextBackground": alpha(red, 0.18),
    "diffEditor.insertedLineBackground": alpha(green, 0.1),
    "diffEditor.removedLineBackground": alpha(red, 0.1),
    "merge.currentHeaderBackground": alpha(teal, 0.3),
    "merge.currentContentBackground": alpha(teal, 0.12),
    "merge.incomingHeaderBackground": alpha(green, 0.3),
    "merge.incomingContentBackground": alpha(green, 0.12),
    "peekView.border": purple,
    "peekViewEditor.background": bg,
    "peekViewEditor.matchHighlightBackground": alpha(teal, 0.2),
    "peekViewResult.background": bgPanel,
    "peekViewResult.fileForeground": fgStrong,
    "peekViewResult.lineForeground": fgFaint,
    "peekViewResult.matchHighlightBackground": alpha(teal, 0.25),
    "peekViewResult.selectionBackground": bgSelected,
    "peekViewResult.selectionForeground": fgStrong,
    "peekViewTitle.background": bgRaised,
    "peekViewTitleLabel.foreground": fg,
    "peekViewTitleDescription.foreground": fgFaint,
    "notebook.editorBackground": bg,
    "notebook.cellEditorBackground": bg,
    "notebook.cellBorderColor": border,
    "notebook.focusedCellBorder": purple,
    "notebook.focusedEditorBorder": purple,
    "notebook.focusedCellBackground": alpha(teal, 0.04),
    "notebook.selectedCellBackground": bgSelected,
    "debugToolBar.background": bg,
    "debugToolBar.border": border,
    "debugConsole.errorForeground": red,
    "debugConsole.warningForeground": warm,
    "debugConsole.infoForeground": teal,
    "debugIcon.breakpointForeground": red,
    "debugIcon.startForeground": green,
    "debugIcon.stopForeground": red,
    "debugIcon.pauseForeground": teal,
    "debugIcon.continueForeground": green,
    "debugIcon.restartForeground": green,
    "debugIcon.stepOverForeground": teal,
    "debugIcon.stepIntoForeground": teal,
    "debugIcon.stepOutForeground": teal,
    "debugIcon.disconnectForeground": red,
    "gitDecoration.addedResourceForeground": green,
    "gitDecoration.modifiedResourceForeground": teal,
    "gitDecoration.deletedResourceForeground": red,
    "gitDecoration.untrackedResourceForeground": green,
    "gitDecoration.ignoredResourceForeground": fgFaint,
    "gitDecoration.conflictingResourceForeground": warm,
    "gitDecoration.stageModifiedResourceForeground": teal,
    "gitDecoration.stageDeletedResourceForeground": red,
    "editorWidget.background": bg,
    "editorWidget.foreground": fg,
    "editorWidget.border": border,
    "editorSuggestWidget.background": bg,
    "editorSuggestWidget.foreground": fg,
    "editorSuggestWidget.border": border,
    "editorSuggestWidget.selectedBackground": bgSelected,
    "editorSuggestWidget.selectedForeground": fgStrong,
    "editorSuggestWidget.highlightForeground": purple,
    "editorHoverWidget.background": bg,
    "editorHoverWidget.foreground": fg,
    "editorHoverWidget.border": border,
    "quickInput.background": bg,
    "quickInput.foreground": fg,
    "quickInputList.focusBackground": bgSelected,
    "quickInputList.focusForeground": fgStrong,
    "quickInputTitle.background": bgRaised,
    "scm.providerBorder": border,
    "problemsErrorIcon.foreground": red,
    "problemsWarningIcon.foreground": warm,
    "problemsInfoIcon.foreground": teal,
  },
  tokenColors: [
    { name: "Comment", scope: ["comment", "punctuation.definition.comment"], settings: { foreground: fgComment, fontStyle: "italic" } },
    { name: "Comment Doc", scope: ["comment.block.documentation", "comment.line.documentation"], settings: { foreground: fgComment, fontStyle: "italic" } },
    { name: "String", scope: ["string", "string.quoted", "string.template"], settings: { foreground: tealText } },
    { name: "String Escape", scope: ["constant.character.escape"], settings: { foreground: green } },
    { name: "Template Expression", scope: ["meta.template.expression", "punctuation.definition.template-expression"], settings: { foreground: fgComment } },
    { name: "Number", scope: ["constant.numeric"], settings: { foreground: red } },
    { name: "Constant", scope: ["constant.language", "constant.other"], settings: { foreground: red } },
    { name: "Variable", scope: ["variable", "variable.other"], settings: { foreground: fg } },
    { name: "Variable Parameter", scope: ["variable.parameter"], settings: { foreground: paramBrown } },
    { name: "Property", scope: ["variable.other.property", "meta.property.object", "support.variable.property"], settings: { foreground: propBlue } },
    { name: "Keyword", scope: ["keyword", "keyword.control", "keyword.operator.expression"], settings: { foreground: purple, fontStyle: "" } },
    { name: "Storage", scope: ["storage.type", "storage.modifier"], settings: { foreground: purple } },
    { name: "Type", scope: ["entity.name.type", "entity.name.class", "support.class", "support.type"], settings: { foreground: warm } },
    { name: "Builtin Type", scope: ["support.type.primitive", "support.type.builtin"], settings: { foreground: warm } },
    { name: "Function", scope: ["entity.name.function", "support.function", "meta.function-call.generic"], settings: { foreground: fnBlue } },
    { name: "Method", scope: ["meta.function-call entity.name.function", "variable.function"], settings: { foreground: fnBlue } },
    { name: "Decorator", scope: ["meta.decorator", "punctuation.decorator", "entity.name.function.decorator"], settings: { foreground: red } },
    { name: "Operator", scope: ["keyword.operator", "punctuation.separator"], settings: { foreground: fgMuted } },
    { name: "Punctuation", scope: ["punctuation"], settings: { foreground: fgComment } },
    { name: "Regex", scope: ["string.regexp"], settings: { foreground: green } },
    { name: "Tag", scope: ["entity.name.tag"], settings: { foreground: purple } },
    { name: "Tag Attribute", scope: ["entity.other.attribute-name"], settings: { foreground: paramBrown } },
    { name: "Markdown Heading", scope: ["markup.heading", "entity.name.section"], settings: { foreground: warm, fontStyle: "bold" } },
    { name: "Markdown Link", scope: ["markup.underline.link"], settings: { foreground: fnBlue } },
    { name: "Markdown Bold", scope: ["markup.bold"], settings: { foreground: purple, fontStyle: "bold" } },
    { name: "Markdown Italic", scope: ["markup.italic"], settings: { foreground: tealText, fontStyle: "italic" } },
    { name: "Markdown Code", scope: ["markup.inline.raw", "markup.fenced_code"], settings: { foreground: fnBlue } },
    { name: "JSON Key", scope: ["support.type.property-name.json"], settings: { foreground: propBlue } },
    { name: "Invalid", scope: ["invalid"], settings: { foreground: white, background: red } },
  ],
  semanticTokenColors: {
    "variable.readonly": { foreground: red },
    "variable.defaultLibrary": { foreground: fnBlue },
    "property.readonly": { foreground: propBlue },
    "parameter": { foreground: paramBrown },
    "class": { foreground: warm },
    "interface": { foreground: warm },
    "enum": { foreground: warm },
    "type": { foreground: warm },
    "typeParameter": { foreground: paramBrown, italic: true },
    "function": { foreground: fnBlue },
    "method": { foreground: fnBlue },
    "namespace": { foreground: warm },
    "keyword": { foreground: purple },
    "decorator": { foreground: red },
    "regexp": { foreground: green },
  },
};

export default theme;
