import { alpha, type Theme } from "../util.ts";

// ---- Palette ----------------------------------------------------------

// Backgrounds (lightest → darkest)
const bg = "#fafbf7";
const bgPanel = "#eef1ea";
const bgRaised = "#e6ebe1";
const bgHover = "#e0e6d8";
const bgSelected = "#d6dfce";
const bgButtonHover = "#c8d3be";
const bgInactiveTab = "#dde3d6";
const bgMinimap = "#f0f3eb";

// Text
const fg = "#1a2a1a";
const fgStrong = "#3a4a35";
const fgMuted = "#6b7565";
const fgComment = "#7d8c75";
const fgFaint = "#aab8a0";
const fgPunct = "#5a6855";

// Borders / guides
const border = "#d2d8c8";
const guide = "#e2e6db";

// Family accents
const green = "#00a000";
// White text is 3.5:1 on `green`: fills take the lightest green that reaches 4.5:1,
// and links a deeper one to clear 4.5:1 on the panel background too.
const greenFill = "#008a00";
const greenFillHover = "#007700";
const greenText = "#007f00";
const blue = "#2a94d6";

// Token-only colours
const teal = "#007575";
const purple = "#6c4bc1";
const purpleDeep = "#5b3fb0";
const fnBlue = "#1f6e8c";
const orangeText = "#b85a00";

// Standard / shared semantics
const red = "#cd0365";
const orange = "#e7645c";
const lightGreen = "#4cd07a";
const lightOrange = "#f5a070";
const lightBlue = "#6ab7e8";
const lightCyan = "#9ee0d6";
const lightPurple = "#b4a3e8";
const tealAccent = "#7bcdc2";
const ansiBrightBlack = "#7a8a78";
const warm = "#b85a00";
const white = "#ffffff";
const black = "#000000";
const transparent = "#00000000";

// ---- Theme ------------------------------------------------------------

const theme: Theme = {
  $schema: "vscode://schemas/color-theme",
  name: "micro:bit Pixel Light",
  type: "light",
  semanticHighlighting: true,
  colors: {
    "editor.background": bg,
    "editor.foreground": fg,
    "editor.lineHighlightBackground": alpha(green, 0.05),
    "editor.lineHighlightBorder": transparent,
    "editor.selectionBackground": alpha(blue, 0.18),
    "editor.inactiveSelectionBackground": alpha(blue, 0.18),
    "editor.findMatchBackground": alpha(green, 0.1),
    "editor.findMatchHighlightBackground": alpha(green, 0.1),
    "editor.wordHighlightBackground": alpha(green, 0.1),
    "editorCursor.foreground": green,
    "editorLineNumber.foreground": fgFaint,
    "editorLineNumber.activeForeground": fg,
    "editorBracketMatch.background": alpha(green, 0.1),
    "editorBracketMatch.border": green,
    "editorWhitespace.foreground": fgFaint + "55",
    "editorIndentGuide.background": guide,
    "editorIndentGuide.activeBackground": fgFaint,
    "editorRuler.foreground": guide,
    "editorBracketHighlight.foreground1": green,
    "editorBracketHighlight.foreground2": blue,
    "editorBracketHighlight.foreground3": purple,
    "editorBracketHighlight.foreground4": green,
    "editorBracketHighlight.foreground5": blue,
    "editorBracketHighlight.foreground6": purple,
    "editorBracketHighlight.unexpectedBracket.foreground": red,
    "editorGutter.background": bg,
    "editorGutter.modifiedBackground": blue,
    "editorGutter.addedBackground": green,
    "editorGutter.deletedBackground": red,
    "titleBar.activeBackground": bgRaised,
    "titleBar.activeForeground": fgStrong,
    "titleBar.inactiveBackground": bgRaised,
    "titleBar.inactiveForeground": fgMuted,
    "titleBar.border": border,
    "activityBar.background": green,
    "activityBar.foreground": white,
    "activityBar.inactiveForeground": alpha(white, 0.62),
    "activityBar.activeBorder": white,
    "activityBar.border": green,
    "modernActivityBarItem.activeForeground": white,
    "modernActivityBarItem.activeBackground": alpha(black, 0.13),
    "modernActivityBarItem.hoverForeground": white,
    "modernActivityBarItem.hoverBackground": alpha(white, 0.13),
    "activityBarBadge.background": red,
    "activityBarBadge.foreground": white,
    "sideBar.background": bgPanel,
    "sideBar.foreground": fgStrong,
    "sideBar.border": border,
    "sideBarTitle.foreground": fgMuted,
    "sideBarSectionHeader.background": bgPanel,
    "sideBarSectionHeader.foreground": fgMuted,
    "sideBarSectionHeader.border": guide,
    "list.activeSelectionBackground": bgSelected,
    "list.activeSelectionForeground": fgStrong,
    "list.inactiveSelectionBackground": bgSelected,
    "list.inactiveSelectionForeground": fgStrong,
    "list.hoverBackground": bgHover,
    "list.hoverForeground": fgStrong,
    "list.focusBackground": bgSelected,
    "list.focusForeground": fgStrong,
    "list.focusOutline": green,
    "list.highlightForeground": green,
    "tree.indentGuidesStroke": guide,
    "editorGroupHeader.tabsBackground": bgRaised,
    "editorGroupHeader.tabsBorder": border,
    "editorGroupHeader.border": border,
    "tab.activeBackground": bg,
    "tab.activeForeground": fg,
    "tab.activeBorderTop": green,
    "tab.activeBorder": bg,
    "tab.inactiveBackground": bgInactiveTab,
    "tab.inactiveForeground": fgMuted,
    "tab.hoverBackground": bgHover,
    "tab.border": border,
    "tab.unfocusedActiveBorderTop": guide,
    "editorGroup.border": border,
    "breadcrumb.background": bg,
    "breadcrumb.foreground": fgMuted,
    "breadcrumb.focusForeground": fg,
    "breadcrumb.activeSelectionForeground": green,
    "statusBar.background": blue,
    "statusBar.foreground": white,
    "statusBar.border": blue,
    "statusBar.noFolderBackground": blue,
    "statusBar.debuggingBackground": greenFill,
    "statusBar.debuggingForeground": white,
    "statusBarItem.hoverBackground": alpha(white, 0.13),
    "statusBarItem.remoteBackground": alpha(black, 0.13),
    "statusBarItem.remoteForeground": white,
    "statusBarItem.prominentBackground": alpha(black, 0.13),
    "statusBarItem.errorBackground": red,
    "statusBarItem.warningBackground": warm,
    "panel.background": bg,
    "panel.border": border,
    "panelTitle.activeForeground": fg,
    "panelTitle.inactiveForeground": fgMuted,
    "panelTitle.activeBorder": green,
    "terminal.background": bg,
    "terminal.foreground": fg,
    "terminal.ansiBlack": fg,
    "terminal.ansiRed": red,
    "terminal.ansiGreen": green,
    "terminal.ansiYellow": orange,
    "terminal.ansiBlue": blue,
    "terminal.ansiMagenta": purple,
    "terminal.ansiCyan": tealAccent,
    "terminal.ansiWhite": fg,
    "terminal.ansiBrightBlack": ansiBrightBlack,
    "terminal.ansiBrightRed": orange,
    "terminal.ansiBrightGreen": lightGreen,
    "terminal.ansiBrightYellow": lightOrange,
    "terminal.ansiBrightBlue": lightBlue,
    "terminal.ansiBrightMagenta": lightPurple,
    "terminal.ansiBrightCyan": lightCyan,
    "terminal.ansiBrightWhite": black,
    "minimap.background": bgMinimap,
    "minimap.selectionHighlight": green,
    "minimapSlider.background": alpha(green, 0.1),
    "minimapSlider.hoverBackground": alpha(green, 0.1),
    "minimapSlider.activeBackground": alpha(green, 0.1),
    "minimapGutter.modifiedBackground": blue,
    "minimapGutter.addedBackground": green,
    "minimapGutter.deletedBackground": red,
    "input.background": bg,
    "input.foreground": fg,
    "input.border": border,
    "input.placeholderForeground": fgMuted,
    "inputOption.activeBorder": green,
    "dropdown.background": bg,
    "dropdown.foreground": fg,
    "dropdown.border": border,
    "button.background": greenFill,
    "button.foreground": white,
    "button.hoverBackground": greenFillHover,
    "button.secondaryBackground": bgSelected,
    "button.secondaryForeground": fgStrong,
    "button.secondaryHoverBackground": bgButtonHover,
    "badge.background": greenFill,
    "badge.foreground": white,
    "notificationCenter.border": border,
    "notifications.background": bgPanel,
    "notifications.foreground": fgStrong,
    "notifications.border": border,
    "textLink.foreground": greenText,
    "textLink.activeForeground": greenText,
    "editorLink.activeForeground": greenText,
    "focusBorder": green,
    "contrastBorder": transparent,
    "scrollbar.shadow": alpha(black, 0.13),
    "scrollbarSlider.background": alpha(fgFaint, 0.27),
    "scrollbarSlider.hoverBackground": alpha(fgFaint, 0.4),
    "scrollbarSlider.activeBackground": alpha(fgFaint, 0.53),
    "diffEditor.insertedTextBackground": alpha(green, 0.18),
    "diffEditor.removedTextBackground": alpha(red, 0.18),
    "diffEditor.insertedLineBackground": alpha(green, 0.1),
    "diffEditor.removedLineBackground": alpha(red, 0.1),
    "merge.currentHeaderBackground": alpha(blue, 0.3),
    "merge.currentContentBackground": alpha(blue, 0.12),
    "merge.incomingHeaderBackground": alpha(green, 0.3),
    "merge.incomingContentBackground": alpha(green, 0.12),
    "peekView.border": green,
    "peekViewEditor.background": bg,
    "peekViewEditor.matchHighlightBackground": alpha(blue, 0.2),
    "peekViewResult.background": bgPanel,
    "peekViewResult.fileForeground": fgStrong,
    "peekViewResult.lineForeground": fgFaint,
    "peekViewResult.matchHighlightBackground": alpha(blue, 0.25),
    "peekViewResult.selectionBackground": bgSelected,
    "peekViewResult.selectionForeground": fgStrong,
    "peekViewTitle.background": bgRaised,
    "peekViewTitleLabel.foreground": fg,
    "peekViewTitleDescription.foreground": fgFaint,
    "notebook.editorBackground": bg,
    "notebook.cellEditorBackground": bg,
    "notebook.cellBorderColor": border,
    "notebook.focusedCellBorder": green,
    "notebook.focusedEditorBorder": green,
    "notebook.focusedCellBackground": alpha(blue, 0.04),
    "notebook.selectedCellBackground": bgSelected,
    "debugToolBar.background": bg,
    "debugToolBar.border": border,
    "debugConsole.errorForeground": red,
    "debugConsole.warningForeground": warm,
    "debugConsole.infoForeground": blue,
    "debugIcon.breakpointForeground": red,
    "debugIcon.startForeground": green,
    "debugIcon.stopForeground": red,
    "debugIcon.pauseForeground": blue,
    "debugIcon.continueForeground": green,
    "debugIcon.restartForeground": green,
    "debugIcon.stepOverForeground": blue,
    "debugIcon.stepIntoForeground": blue,
    "debugIcon.stepOutForeground": blue,
    "debugIcon.disconnectForeground": red,
    "gitDecoration.addedResourceForeground": green,
    "gitDecoration.modifiedResourceForeground": blue,
    "gitDecoration.deletedResourceForeground": red,
    "gitDecoration.untrackedResourceForeground": green,
    "gitDecoration.ignoredResourceForeground": fgFaint,
    "gitDecoration.conflictingResourceForeground": warm,
    "gitDecoration.stageModifiedResourceForeground": blue,
    "gitDecoration.stageDeletedResourceForeground": red,
    "editorWidget.background": bg,
    "editorWidget.foreground": fg,
    "editorWidget.border": border,
    "editorSuggestWidget.background": bg,
    "editorSuggestWidget.foreground": fg,
    "editorSuggestWidget.border": border,
    "editorSuggestWidget.selectedBackground": bgSelected,
    "editorSuggestWidget.selectedForeground": fgStrong,
    "editorSuggestWidget.highlightForeground": green,
    "editorHoverWidget.background": bg,
    "editorHoverWidget.foreground": fg,
    "editorHoverWidget.border": border,
    "quickInput.background": bg,
    "quickInput.foreground": fg,
    "quickInputList.focusBackground": bgSelected,
    "quickInputList.focusForeground": fgStrong,
    "quickInputTitle.background": bgRaised,
    "scm.providerBorder": border,
    "problemsErrorIcon.foreground": red,
    "problemsWarningIcon.foreground": warm,
    "problemsInfoIcon.foreground": blue,
  },
  tokenColors: [
    { name: "Comment", scope: ["comment", "punctuation.definition.comment"], settings: { foreground: fgComment, fontStyle: "italic" } },
    { name: "Comment Doc", scope: ["comment.block.documentation", "comment.line.documentation"], settings: { foreground: fgComment, fontStyle: "italic" } },
    { name: "String", scope: ["string", "string.quoted", "string.template"], settings: { foreground: orangeText } },
    { name: "String Escape", scope: ["constant.character.escape"], settings: { foreground: green } },
    { name: "Template Expression", scope: ["meta.template.expression", "punctuation.definition.template-expression"], settings: { foreground: fgPunct } },
    { name: "Number", scope: ["constant.numeric"], settings: { foreground: purple } },
    { name: "Constant", scope: ["constant.language", "constant.other"], settings: { foreground: purpleDeep } },
    { name: "Variable", scope: ["variable", "variable.other"], settings: { foreground: fg } },
    { name: "Variable Parameter", scope: ["variable.parameter"], settings: { foreground: purple } },
    { name: "Property", scope: ["variable.other.property", "meta.property.object", "support.variable.property"], settings: { foreground: fnBlue } },
    { name: "Keyword", scope: ["keyword", "keyword.control", "keyword.operator.expression"], settings: { foreground: teal, fontStyle: "" } },
    { name: "Storage", scope: ["storage.type", "storage.modifier"], settings: { foreground: teal } },
    { name: "Type", scope: ["entity.name.type", "entity.name.class", "support.class", "support.type"], settings: { foreground: red } },
    { name: "Builtin Type", scope: ["support.type.primitive", "support.type.builtin"], settings: { foreground: red } },
    { name: "Function", scope: ["entity.name.function", "support.function", "meta.function-call.generic"], settings: { foreground: blue } },
    { name: "Method", scope: ["meta.function-call entity.name.function", "variable.function"], settings: { foreground: blue } },
    { name: "Decorator", scope: ["meta.decorator", "punctuation.decorator", "entity.name.function.decorator"], settings: { foreground: orangeText } },
    { name: "Operator", scope: ["keyword.operator", "punctuation.separator"], settings: { foreground: fgPunct } },
    { name: "Punctuation", scope: ["punctuation"], settings: { foreground: fgPunct } },
    { name: "Regex", scope: ["string.regexp"], settings: { foreground: green } },
    { name: "Tag", scope: ["entity.name.tag"], settings: { foreground: red } },
    { name: "Tag Attribute", scope: ["entity.other.attribute-name"], settings: { foreground: purple } },
    { name: "Markdown Heading", scope: ["markup.heading", "entity.name.section"], settings: { foreground: red, fontStyle: "bold" } },
    { name: "Markdown Link", scope: ["markup.underline.link"], settings: { foreground: blue } },
    { name: "Markdown Bold", scope: ["markup.bold"], settings: { foreground: teal, fontStyle: "bold" } },
    { name: "Markdown Italic", scope: ["markup.italic"], settings: { foreground: orangeText, fontStyle: "italic" } },
    { name: "Markdown Code", scope: ["markup.inline.raw", "markup.fenced_code"], settings: { foreground: blue } },
    { name: "JSON Key", scope: ["support.type.property-name.json"], settings: { foreground: fnBlue } },
    { name: "Log Error", scope: "token.error-token", settings: { foreground: red } },
    { name: "Log Warning", scope: "token.warn-token", settings: { foreground: warm } },
    { name: "Log Info", scope: "token.info-token", settings: { foreground: fnBlue } },
    { name: "Log Debug", scope: "token.debug-token", settings: { foreground: teal } },
    { name: "Inserted", scope: ["markup.inserted"], settings: { foreground: greenText } },
    { name: "Deleted", scope: ["markup.deleted"], settings: { foreground: red } },
    { name: "Invalid", scope: ["invalid"], settings: { foreground: white, background: red } },
  ],
  semanticTokenColors: {
    "variable.readonly": { foreground: purpleDeep },
    "variable.defaultLibrary": { foreground: blue },
    "property.readonly": { foreground: fnBlue },
    "parameter": { foreground: purple },
    "class": { foreground: red },
    "interface": { foreground: red },
    "enum": { foreground: red },
    "type": { foreground: red },
    "typeParameter": { foreground: purple, italic: true },
    "function": { foreground: blue },
    "method": { foreground: blue },
    "namespace": { foreground: red },
    "keyword": { foreground: teal },
    "decorator": { foreground: orangeText },
    "regexp": { foreground: green },
  },
};

export default theme;
